### ISSUE TITLE
Non-piping practice with backpressure

### ISSUE THREAD

**Issue by yukal** [brianc/node-pg-copy-streams#117]
What is the best practice to use this interface without pipes? Is it possible?

There are few tables in my relational DB, which I trying to fill out with some data from a huge CSV file. But before sending the data to DB, I have to process the data that my script has read. I open 4 streams at the same time and trying to write some data.

```js
async function main() {
  let pgClient;
  const pool = new Pool(config.postgres);

  pool.on("error", function (err) {
    console.error(err);
    pgClient && pgClient.release(true);
  });

  try {
    pgClient = await pool.connect();
    pgClient.on("error", function(err) {
      console.error('[pg-client]', err.message);
      this.release(true);
    });
  } catch (err) {
    return console.error('[pg-client]', err.message);
  }

  const sqlQuery = `
    COPY "${tableName}" ("${escapedFields}") FROM STDIN
    WITH CSV DELIMITER ',' QUOTE '"' ESCAPE '\\' NULL AS ''
  `;

  const table1 = pgClient.query(pgCopyFrom(sqlQuery1, { encoding: "utf8" }));
  const table2 = pgClient.query(pgCopyFrom(sqlQuery2, { encoding: "utf8" }));
  const table3 = pgClient.query(pgCopyFrom(sqlQuery3, { encoding: "utf8" }));
  const table4 = pgClient.query(pgCopyFrom(sqlQuery4, { encoding: "utf8" }));

  // Async Iterations
  {
    table1.write(...);
    table2.write(...);
    table3.write(...);
    table4.write(...);
  }
}

main();
```

I have never worked with streams, and I have already read some documentation about it. But I still don't understand how can I use it with this interface. In the case when I do not control the number of writes the `backpressure` is growing for obvious reasons, but when I trying to control it the `drain` event is not emits for each stream.
What am I doing wrong, and how can I use It without pipes carefully processing the `backpressure`?

**Comment by jeromew** [comment]
Hello,
thanks for your report.

I have not investigated this kind of usage, but there is something that seems weird in your code : you should be using a different pgClient for each query since you seem to be willing to insert data in parallel in the 4 tables.

From my current understanding of your use case, the code would currently wait for the query on table1 to be finished before inserting anything into table2 and so on.

This problem may have been hidden in your tests because there are buffers in the streams and they are accepting the data to some extent, but it surely could lead to some weird things happening and creating 4 clients would be the first thing I would test.

Other than that, tableN are writable streams and should have usual behavior regarding backpressure but I must admit that I never had an issue that needed to investigate on this.

I hope this helps.

**Comment by yukal** [comment]
Well, I've already tested the code with different clients for each table and actually it works but I have got an error about the call stack exceeded. I think you should use `setImmediate` or `process.nextTick` instead of calling the callback directly in a handler.

**Comment by yukal** [comment]
Hello, @jeromew. I don't know what exactly happened, but it seems it works. I have three parent and five children tables. I have created different clients for each query as you recommended, and then I write to all streams consistently. And, yeah, it works perfectly. It's no need to use `setImmediate` or `process.nextTick`, the idea to use these methods was to keep the event loop open. Thank you, @jeromew :)
I think we can close this issue.
