### ISSUE TITLE
Question: is it possible to get the line number of the file where copy failed?

### ISSUE THREAD

**Issue by arajczy** [brianc/node-pg-copy-streams#129]
Hello,

I would like to re-run file copy excluding the line of the file where the error occurs. Is it possible to get the line number of the file where the copy progress failed?

Thanks

**Comment by jeromew** [comment]
Hello,

as far as I know, the COPY operation is atomic so you would need to re-run the COPY anyway if an error occurs. Am I misunderstanding something ?

**Comment by arajczy** [comment]
Yes, but if I run copy from postgres cli it gives me the erroneaous line number pg-copy-streams does not.

Postgres cli error message:

> ERROR:  null value in column "DDI" of relation "accounts" violates not-null constraint
> DETAIL:  Failing row contains ([...]).
> CONTEXT:  COPY accounts, **line 17147**: [...]

pg-copy-streams error message:

> null value in column "DDI" of relation "accounts" violates not-null constraint

**Comment by jeromew** [comment]
Ok I understand it is more for detecting on which line in the source file the problem is ; or how many rows have been sent before the error.
it would be interesting to know where the postgres cli gets this information from. Is it coming from postgres when the error is received or does the cli keep track of the lines it is sending ?
currently `pg-copy-streams` does not track the lines as this would add more work and impact performance.

**Comment by arajczy** [comment]
I have found the answer in _error.where_

**Comment by jeromew** [comment]
ok thanks for finding the solution !
