### ISSUE TITLE
Error: Release called on client which has already been released to the pool.

### ISSUE THREAD

**Issue by FacundoMartinezCampos** [brianc/node-pg-copy-streams#135]
Im trying to pipe from a file to table using basically the same code of the examples and im getting this error

![image](https://user-images.githubusercontent.com/54776310/181643272-b10605ae-4125-4f97-ab87-1a10a38e76be.png)
![image](https://user-images.githubusercontent.com/54776310/181643342-23eac364-3590-4d9f-99c6-c1dcfc079a5c.png)

aside from the pool conection, i have another client conection running at the same time, i dont know if this is the problem.

**Comment by jeromew** [comment]
Hello,

The pg-pool error message states that that client you received was [released more than once](https://github.com/brianc/node-postgres/blob/68160a29bd8dfe97c74ab9a74000977da7783d6f/packages/pg-pool/index.js#L26).
It is probably because the "done" callback is called several times ; you have 3 events registered that can potentially call "done". In order to dig further and understand is happening it would be necessary to understand which is called, and when.

Do not hesitate to create a test case following the examples in the test directory in order to reproduce the error.

**Comment by FacundoMartinezCampos** [comment]
Hello!

Thanks for answering, as you said, it was because an error on the fileStream event, i replaced the done function with console.logs and i saw the error.

Thank you for your time!
