### ISSUE TITLE
help needed: concurrent requests

### ISSUE THREAD

**Issue by ilteoood** [brianc/node-pg-copy-streams#154]
Hi everyone,
I've made the following repro to better explain my situation: https://github.com/ilteoood/pg-copy-repro.

My data source (received from third parties), consist of a series of `activities` with their `consumptions`.
What I do with my code, is to separate them using 2 different streams in order to being able to insert them in 2 different tables: `activities` and `activities_consumptions`.

To speed up things, I try to insert data in both the tables concurrently, but without luck: in fact, once the high water mark is reached, no more data flows through the stream.

The same doesn't happen if I completely remove the code for the `activitiesConsumptionStream`.

Does the library support concurrent copy in different tables? What am I doing wrong?

Thanks you so much for every support you'll provide.

**Comment by jeromew** [comment]
Hello,

thanks for the report and thanks for the repro code which makes things a lot more easy to reason about.

COPY is like an sql query in postgres. A client can only process one query at a time, even though `pg` internally buffers all queries sent to the client.

So in your repro code, the second COPY operation will not be active until the first one has completely finished which creates a problem because all consumptions flowing are buffered into the internal stream buffer of consumptionsCopy which hits the highwatermark which leads to the ~deadlock

you should be able to fix it by creating a second postgres client, replacing

`const client = await transaction.client.acquireConnection()
`
by

```
const activitiesClient= await transaction.client.acquireConnection()
const consumptionsClient = await transaction.client.acquireConnection()
```

but you will not be able to have one postgres transaction wrapping both COPY operations and still keep the benefits of streaming. 

If the postgres transaction is absolutely needed and as a consequence the 2 COPY operations need to happen on the same client, then you will have to buffer the consumptions somehow (increasing the highwaterMark and accept the memory consumption, or streaming consumptions into an intermediary file for example)

**Comment by ilteoood** [comment]
Hi @jeromew, thank you so much for the time you spent looking into this.
I've an additional question for you, which I don't understand: why the unique client works when the sources of data instead of being 2 readable streams managed by me, are both an fs.createReadStream? Following what you said, it should not work either 🤔

I can change the repro to show you that, but is quite easy to redirect the output of the data source to a file than read it

**Comment by ilteoood** [comment]
Here is another branch that uses `fs` streams with a single client, which works without issues: https://github.com/ilteoood/pg-copy-repro/tree/repro-fs

**Comment by jeromew** [comment]
Hello,

I believe the repro-fs working can be explained because it does not have the same flowing structure.

```
main :
generateData |=> activitiesCopy
                       |=> consumptionsCopy

```
while

```
repro-fs
activities.csv          |=> activitiesCopy
consumptions.csv |=> consumptionsCopy

```

The backpressure on the consumption pipeline in repro-fs still exists, but it does not stop the flow on the activities pipeline.
So the activities COPY operation can finish and then `pg` starts the consumption COPY operation which releases the consumptions pipeline that can do its things.

**Comment by jeromew** [comment]
Note that another way to keep the postgres transaction would be to transform the source stream into a flattened stream where each line has a consumption + and activity


```
start transaction
COPY would direct the flow into a `activity+consumption` table (could be a tmp table)
INSERT would select the distinct activities and put them in the activities table
INSERT would select the consumptions joined wih the activities table and put them into the consumptions table
commit
```

**Comment by jeromew** [comment]
Can we close this issue ?
