### ISSUE TITLE
pipe copyFrom into copyTo gets stuck 

### ISSUE THREAD

**Issue by LaurentAtGreenly** [brianc/node-pg-copy-streams#160]
It seems piping is broken after the first chunk of data is sent:

```javascript
  const source = db.query(copyTo(`COPY (SELECT * FROM source_test) TO STDOUT`));
  const target = db.query(copyFrom('COPY target_test FROM STDIN'));
  await pipeline(source, target);
```

This will work fine for a source table filled like 

```SQL
insert into source_test(value) (SELECT generate_series(1, 10000) as value);
```

But above a treshold, the pipe gets stuck (13000 in my case)

In that case, I cannot use the ``copyBoth`` with replication slot as in the test file. I just want to use streaming feature from nodejs (handler back pressure etc) and it seems to me that the issue is more related to node stream plumbing in that case

**Comment by jeromew** [comment]
Hello,

thanks for the report.
I think your problem comes from the fact that you use the same db connection to create source & target.
the consequence is that target COPY never reaches postgres because one connection can only execute one query at a time (the other query is queued inside `pg`)
so source can pipe into the node.js target stream only until its highwatermark is full and then the pipeline gets stuck.

I think a solution would be to have 2 different clients :

```
  const source = db1.query(copyTo(`COPY (SELECT * FROM source_test) TO STDOUT`));
  const target = db2.query(copyFrom('COPY target_test FROM STDIN'));
  await pipeline(source, target);
```

keep me posted and don't hesitate to close the issue if it works.

**Comment by LaurentAtGreenly** [comment]
you are correct. Thanks a lot ! (blazing fast)
