### ISSUE TITLE
Using 'pg', 'pg-copy-streams' together do not use connection pool properly

### ISSUE THREAD

**Issue by cbaron** [brianc/node-pg-copy-streams#40]
https://gist.github.com/cbaron/963311847387b96925cb628a62907c82

**Comment by brianc** [comment]
Hey @cbaron - thanks so much for the example code! I probably wont have
time to look at this until mid summer or so in my free time.  If it's
important it gets fixed for you/your team promptly, I am happy to engage on
a consulting basis if you'd like - you can email me at
brian.m.carlson@gmail.com.  Otherwise, I will always take some time out to
review pull requests for bug fixes or new features if they include tests!
:heart:

**Comment by jeromew** [comment]
pg pool is a moving target for me + old pooling has been removed from the code base; your gist does not seem to comply with https://github.com/brianc/node-postgres#client-pooling
+ I am not sure that pg still accepts sync stacking of queries

I am not sure I can help here at this stage + the issue seem to have stalled ; I am closing this issue for now. Feel free to re-open if necessary. The best would be with a working test scenario that fits in the current test setup.
