### ISSUE TITLE
the efficiency of pg-copy-streams is very low

### ISSUE THREAD

**Issue by fwjieok** [brianc/node-pg-copy-streams#56]
This library efficiency is relatively low, you can find a reason for it, I just began to use the following form:   node  xxx.js  |  PSQL -c  "copy" XXX from STDIN"
This efficiency is relatively high, however, when I use the pg-copy-streams library streamer directly to write data, using the ATOP command to view the performance of the system found that IRQ CPU load is high, and then write the speed is very slow.

i use ubuntu 16.04 os.

**Comment by jeromew** [comment]
Hello, thanks for the report. I don't think the library has really been tested for performance yet so your feedback is interesting. I haven't done it myself.

The value I see in the module is to be able to programmaticaly use COPY to one or several databases without using & maintaining hybrid pipelines (like you mention with unix pipe). It guess it is hard to beat `whatever | psql`

Compared to a stream of "insert" commands coded in node.js, the module using "COPY" is faster.

It would be interesting to dig on the overhead of the module compared to `node xxx.js | PSQL -c "copy" XXX from STDIN`. Reading the code, the overhead of the module shouldn't be that high, the main loop beeing

```
var copyDataBuffer = Buffer([code.CopyData])
CopyStreamQuery.prototype._transform = function(chunk, enc, cb) {
  var Int32Len = 4;
  this.push(copyDataBuffer)
  var lenBuffer = Buffer(Int32Len)
  lenBuffer.writeUInt32BE(chunk.length + Int32Len, 0)
  this.push(lenBuffer)
  this.push(chunk)
  cb()
}
```
and this `Transform` stream is piped into the pg connection for which I don't know the overhead. We might also have a slowdown because of how the node.js streams are used. 

I suspect one culprit for the slowness that you observe is that we use a native node.js `Transform` stream that, by its implementation, does not use `_writev`. The [doc](https://nodejs.org/api/stream.html#stream_duplex_and_transform_streams) states

> It is important to note that all calls to writable.write() that occur between the time writable._write() is called and the callback is called will cause the written data to be buffered. Once the callback is invoked, the stream will emit a 'drain' event. If a stream implementation is capable of processing multiple chunks of data at once, the writable._writev() method should be implemented.


Can you clarify what you mean by "IRQ CPU load is high, and then write the speed is very slow." ?

**Comment by fwjieok** [comment]
Because we are now using postgresql, doing stress tests, using linux atop and iostat command to observe the system performance and observation IO read and write speed, and then found that the use of pg-copy-streams found efficiency is the end, and then through the atop Command to find the system load is high, mainly CPU, atop command shell output interface has an irq field, its high value, through the iostat command to see IO read and write speed has become very slow, probably down 1.5 Times, I do not know why the CPU usage will become so high, my test item is inserted into the postgresql 2 billion data. . .

**Comment by fwjieok** [comment]
I am not sure why the efficiency of pg-cppy-streams so low, but observed atop command output found cpu load high, cpu load parameters in the irq field is unusually high, so guess, you easily test pg-copy -streams performance, compared to unix pipelines

**Comment by jeromew** [comment]
Thanks for the info. I do not have time right now to investigate further + my use case does not currently highlights this issue so it might take some time.

I'll leave this issue open as of now in case someones wants to dig into it, maybe writing a benchmark script to understand the cpu usage. I would bet on the necessity to modify the streaming pipeline to use `_writev`

As of now if you want to use your solution inside node.js, you could probably try to spawn a `psql ..` and pipe into that, without using `pg-copy-streams` at all.

**Comment by jeromew** [comment]
I did some tests comparing

`time seq 0 9999999 | /opt/postgresql-9.6.1/bin/psql postgres -c "COPY number FROM STDIN"
`

with

```
var cp = require('duplex-child-process');
var pg = require('pg')
var copy = require('../').from

var client = function() {
  var client = new pg.Client()
  client.connect()
  return client
}

var c = client();
var seq = cp.spawn('seq', ['0', '9999999'])
var from = c.query(copy('COPY number FROM STDIN'))
seq.pipe(from);
from.on('end', function() {
  c.end()
})
```

I the performance of the node version was better than the psql version (postgres was tested on localhost).

There certainly is more work to do regarding the performance of this module but I am not sure anymore that "the efficiency of pg-copy-streams is very low" compared to psql. Maybe future testing will put a finger on a specific issue with a test case that can be reproduced.
