### ISSUE TITLE
error: there is no parameter $1

### ISSUE THREAD

**Issue by kilianc** [brianc/node-pg-copy-streams#72]
How do I pass parameters?

**Comment by jeromew** [comment]
Hello,
I am closing this issue for now. Feel free to re-open with a real test case if needed
you can also check https://github.com/brianc/node-postgres/issues/920 which is related.

**Comment by eljefedelrodeodeljefe** [comment]
I would reopen this. There doesn't seem to a reason why nested copy statements wouldn't support, also it's very blackboxy why pg opts out of sending them without notice or an error

**Comment by jeromew** [comment]
one year ago I closed this issue from 2 years ago because it is simply not informative enough to understand what is going on. This seemed to be about prepared statements and not about nested copy statements. So I will not re-open this issue.
If you have a new issue and a test case to pinpoint it don't hesitate to create a new issue.
