### ISSUE TITLE
Usage with knex.

### ISSUE THREAD

**Issue by mathieutu** [brianc/node-pg-copy-streams#76]
Hi,
I'm trying to return a stream of a csv from a table.

I have knex on my project, and can't find a way to use this module with is.
```js
getStream() {
    const client = this.knex./* Problem here: how to access to the pg client showed in the readme */

    return client.query(to(`COPY "${this.table}" TO STDOUT WITH CSV HEADER`))
  }
```
I've tried and search everything I've found, without success.
I've tried with `knex.query`, `knex.client.query` seen some things with knex.client.Runner, knex.client.pool.aquire, but didn't succeed to manage it.

I'm also looking for general documentation about this knex "client" object, because I can't find anything on documentation, and don't know where to find it.

Thank you very much,
Matt'.

**Comment by mathieutu** [comment]
Hi again.
I've found something after digging much more in the code.
```ts
async getDriverEmarsysStream(): Promise<Readable> {
    const connection: PoolClient = await this.knex.client.acquireConnection()


    return connection.query(to(`COPY "${this.table}" TO STDOUT WITH CSV HEADER`))
```

It seems to be better, as I have another problem : 
```
 { Error: Cannot find module './undefined/index.js'
    at webpackContextResolve (.webpack/service/src/handlers/webpack:/node_modules/knex/lib/dialects sync ^\.\/.*\/index\.js$:14:1)
    at webpackContext (.webpack/service/src/handlers/webpack:/node_modules/knex/lib/dialects sync ^\.\/.*\/index\.js$:8:1)
    at Knex (.webpack/service/src/handlers/webpack:/node_modules/knex/lib/index.js:49:15)

```

I'm still investigating.

**Comment by jeromew** [comment]
Hello @mathieutu sorry for the delay I guess you found a workaround for your issue.
you sure need to access the underlying postgres client like you did because only pg.client.query knows how to handle the `to` Submittable Object.
I will close this for now as it does not seem to be related to a `pg-copy-stream` bug. Feel free to reopen if needed.

**Comment by nicoburns** [comment]
With modern node and knex, and using transactions:
```javascript
const { promisify } = require('util');
const stream = require('stream');
const copyFrom = require('pg-copy-streams').from;
const pipeline = promisify(stream.pipeline);
const knex = require('knex');

async function copyToTable(txOrKnex, tableName, readableStream) {
  const client = await (txOrKnex.trxClient || txOrKnex.client).acquireConnection();
  await pipeline(
    readableStream,
    client.query(copyFrom(`COPY ${tableName} FROM STDIN WITH (FORMAT csv)`)),
  );
}

knex.transaction(async (tx) => {
    const fileStream = fs.createReadStream("./src/scripts/zipcodes.txt");
    await copyToTable(tx, 'table_name', fileStream);
    
    const stringStream = stream.Readable.from(stringContainingCsvData);
    await copyToTable(tx, 'table_name', stringStream);
});
```
The knex Transaction object has a trxClient property which allows you to acquire the transaction's connection. The top-level has a client property which allows the same outside of a transaction context.

**Comment by Zyles** [comment]
Do you have a working example for 2021? My knex does not have .query function. I tried using .raw but got sql.replace error.

**Comment by jeromew** [comment]
Hello, thanks for your report.

I'll leave this open for a few days in case @nicoburns is still using the library and has any idea on what is your problem.

But this is not an issue with this module. In order to use this module, you need to have access to the raw driver connection and it can only be the pg module.

**Comment by nicoburns** [comment]
@Zyles It sounds like you're trying to use pg-copy-streams woth knex.raw which won't work. You need the underlying node-pg client which can be accessed via `knex.client`. So try `knex.client.query`

@jeromew IIRC last time this issue was brought up knex was in the middle of a refactor. Would it be possible to expose a `.client()` method or similar that works from both the top level knex object (checks a client out of the pool) and on a transaction (returns the client that the transaction is using), and can be comitted to as a stable documented API. That would make these use cases where you need to drop down to the raw pg level much nicer ane more future proof.

**Comment by brianc** [comment]
> Would it be possible to expose a `.client()` method or similar that works from both the top level knex object (checks a client out of the pool) and on a transaction (returns the client that the transaction is using), and can be comitted to as a stable documented API. That would make these use cases where you need to drop down to the raw pg level much nicer ane more future proof.

if the knex team does that we're golden....but you'll have to ask them for that feature

**Comment by nicoburns** [comment]
Ah, thought this was the knex repo. Oops.
