### ISSUE TITLE
usage with `stream.pipeline` 

### ISSUE THREAD

**Issue by tswaters** [brianc/node-pg-copy-streams#86]
Hi,

I'm trying to use this module to copy data from one environment to another while applying mutations to the data in transit.  This works really well, but I find that when using the `pipeline` function exported by node core (https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback), it comes back too quickly and the database is still processing the entries it has received after the process exits

Here's what my code looks like right now --

```
exports.transfer = (sourceClient, targetClient) =>
	new Promise((resolve, reject) =>
		pipeline(
			sourceClient.query(to('COPY mytable TO stdout')),
			new MyFirstTransformer(),
			new MySecondTransformer(),
			new SomeOtherTransformer(),
			targetClient.query(from('COPY mytable FROM stdin')),
			(err, res) => (err ? reject(err) : resolve())
		)
	)
```

The code works correctly, I've just noticed that if I check the target database afterwards, the `COPY` command is still running after my process has finished.

I've noted the following appears in this readme:

> Even if pg-copy-streams.from is used as a Writable (via pipe), you should not listen for the 'finish' event and expect that the COPY command has already been correctly acknowledged by the database. Internally, a duplex stream is used to pipe the data into the database connection and the COPY command should be considered complete only when the 'end' event is triggered.

I'm wondering if this may be related?  Maybe `finish` is being fired, `pipeline` picks it up & fires the callback...  any recommendations for a way to avoid this ?

I suppose I could use `pipe` manually -- this is a relatively new function from nodejs so maybe it doesn't fully support edgy cases like this.

**Comment by tswaters** [comment]
I'm working around it with the following:

```
exports.transfer = (sourceClient, targetClient) =>
	new Promise((resolve, reject) => {
		const sourceStream = sourceClient.query(to('COPY mytable TO stdout'))
		const targetStream = targetClient.query(from('COPY mytable FROM stdin'))
		const final = [
			new MyFirstTransformer(),
			new MySecondTransformer(),
			new SomeOtherTransformer()
		].reduce((memo, transform) => memo.pipe(transform), sourceStream)

		final.pipe(targetStream)
		targetStream.on('end', resolve)
		targetStream.on('error', reject)
		final.on('finish', () => process.stderr.write('fin\n'))
	})
```

I'll wait until the target stream finishes before proceeding.

**Comment by jeromew** [comment]
Hello, thanks for you report and sorry for the delay.

You are right that this is a case where the readme note is important (which is why your home-made pipeline works in your second message)

The problem we have is that the visible pipeline in the code is `to > tr1 > tr2 > tr3 > from`.

But under the hood, the stream pipeline involves the connections `cnx1 > to > tr1 > tr2 > tr3 > from >cnx2`

From what I can read in the `pipeline` implementation - https://github.com/nodejs/node/blob/9edce1e12a7b69e7986dd15fce18d6e46590161a/lib/internal/streams/pipeline.js (which is somewhat complex, probably for good reasons), it considers the last element of the pipeline only for its writable role, which leads the code to rely on the 'finish' event.

As you saw in the readme note, this is not correct when working with the current implementation of the `pg-copy-stream` module.

We should probably try and make this use case work (I added the note in the readme because it is currently the only way to correctly detect the end of the COPY but it does not feel right) but these streams / event orchestrations sometimes lead to subtle bugs. Maybe there is a way to delay the triggering of the finish event after the `command complete` is received from the pg server.

**Comment by pspi** [comment]
There's a good chance https://github.com/brianc/node-pg-copy-streams/pull/103 and https://github.com/brianc/node-pg-copy-streams/pull/102 fixed this issue.

**Comment by jeromew** [comment]
@tswaters if you can find some time I would be very interested if you could test your issue against 4.0.0 which was just published.
This version should be more robust regarding integration with `finished` and `pipeline`

note that this is a breaking change and you will need to wait on copy-from 'finish' event. copy-from is now a pure writable as expected and will not emit an 'end' event anymore.

I'll leave this open for a few days.

**Comment by jeromew** [comment]
Feel free to re-open if needed.

**Comment by tswaters** [comment]
Thanks! I'll be sure to give the new version a try and will report back here if I encounter any difficulties.
